[build]
builder = "DOCKERFILE"
dockerfilePath = "src/MoodTracker.Api/Dockerfile"
dockerContext = "."

[deploy]
healthcheckPath = "/health/live"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
